openapi: 3.0.3
info:
  title: Wisdom Connect2 API
  version: 1.0.0
  description: Wisdom Connect2 API Swagger Documentation and Testing
paths:
  /:
    get:
      summary: Testing Route
      tags:
        - Test
      responses:
        "200":
          description: Return a simple success message
  /auth/:
    get:
      summary: Auth Route
      tags:
        - Auth
      responses:
        "200":
          description: Return a simple success message
  /auth/register:
    post:
      summary: Registration Route
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                email:
                  type: string
                  format: email
                role:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
                - role
                - name
                - username
      responses:
        "200":
          description: "Successfully Registered"
  /auth/login:
    post:
      summary: User Login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: "Successfully Logged In"
  /user/:
    get:
      summary: Test user route
      tags:
        - User
      responses:
        "200":
          description: Return a simple success message
  /user/profile:
    get:
      summary: Get User Profile
      tags:
        - User
      responses:
        "200":
          description: Return user profile information
  /user/update:
    put:
      summary: Update User Profile
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                email:
                  type: string
                  format: email
                role:
                  type: string
              required:
                - email
      responses:
        "200":
          description: "Successfully Updated User Profile"
  /user/delete:
    delete:
      summary: Delete User Account
      tags:
        - User
      responses:
        "200":
          description: "Successfully Deleted User Account"
  